### ISSUE TITLE
Camera wedges

### ISSUE THREAD

**Issue by meshula** [usd-wg/OpenUSD-proposals#1]
What would be the least painful way to capture wedges that vary across multiple aspects of a camera model? For example, one may shoot a wedge varying fstop and exposure duration.,

**Comment by revisionfx** [comment]
Question about draft proposal

If you select a DOF table, example p 15 below - 32 mm  T/2.8 mm aperture, 10 M to avoid INF 
[](https://www.cookeoptics.com/wp-content/uploads/2021/11/Anamorphic-i-DoF-Tables_20161010.pdf)
Is your formula working for you for Near and Far ?

Second can near and far be used by a renderer for linearly scaling DOF before Distance and after distance where "pixel size" is 1 from Near to Far?

**Comment by revisionfx** [comment]
> What would be the least painful way to capture wedges that vary across multiple aspects of a camera model? For example, one may shoot a wedge varying fstop and exposure duration.,

DO you mean how to store a table of inter-connected variables (e.g. the DOF table in table I link to in following thread?) - As in for regular zoom where you only have a table for near and far of zoom range....?

**Comment by meshula** [comment]
> e.g. the DOF table in table I link to in following thread? 

Could you post the link you're referring to here?

> Second can near and far be used by a renderer for linearly scaling DOF before Distance and after distance where "pixel size" is 1 from Near to Far?

Near and far in the schema are just meant for clipping. We provide a formula for computing the hyperfocal distance from a circle of confusion, but we don't provide one to compute a DOF from a CoC as is typical. The formula for DOF simulation is itself non-linear, so I'd wager the answer to your question is no. I stand to be corrected of course.

**Comment by revisionfx** [comment]
Sorry I did not realize we were in a different thread
https://www.cookeoptics.com/wp-content/uploads/2021/11/Cooke-Lenses-DoF-Tables-20161010.pdf

This is in reference to:  
       Dn = hd / (h + (d - f))
       Df = hd / (h - (d - f))

**Comment by meshula** [comment]
Ah, those equations are reproduced in the schema. Dn and Df give you the range of distances for which the image is in focus. They don't tell you to what degree things are out of focus outside of that range; you could linearly scale as you suggest, but that would be "a" model, and not motivated by anything in our proposal.

That Cooke table is very interesting. Would we want to be able to carry such data?

By wedges, I was meaning like when you go out on a shoot, and shoot something at the measured exposure, and at two other exposures. My question was along the lines of would that be a different set of overrides on some base prim? The Cooke table suggests that wedges could be tabular.

**Comment by revisionfx** [comment]
I see... check this page:
https://eztrack.studio/lens-calibration/fundamental-lens-calibration-parameters-for-virtual-production/
Scroll to the end dynamic representation
Since it's USD could be a sort of mesh maybe :)

**Comment by meshula** [comment]
Different semantic interpretation, but I see your point.

**Comment by revisionfx** [comment]
The table is a cheat sheet for focus puller
The point is to see if the formula approximation match the published tables
Sanity test should be done with a prime lens tables, any DOF table you google would do. Note the Coc/Cof bundled in the Hyperfocal formula is sort of a subjective value, whether you use 0.01, 0.015, 0.02, 0.03 will change Near and Far focal zone - DOF range. The main use case is to have the correct shallow DOF falloff,  as far as I know people just eyeball it these days. So at largest distance, if the near and far focus deviate differently from focal distance (e.g. 1/3 <- FD -> 2/3   )...

**Comment by revisionfx** [comment]
@meshula  - if you need to make stacks, bracketed shots - I have some BGH-1 cameras that I could loan you, they have a C API to control from a PC  with ehternet connection that is decent. You could with that make loops of capture wihich slides different parameters...  At least it's a qualified camera in real production unlike machine vision cameras...

**Comment by meshula** [comment]
That's a lovely offer, thank you! My goal at the moment is to help the team get this proposal written though :)
